// packages/server/src/routes/provider/privacy-policy.svelte
<script>
  import { PrivacyPolicyContent } from "@upswyng/common";
  import insane from "insane";

  $: sanitizedPrivacyPolicyContent = insane(PrivacyPolicyContent, {
    ...insane.defaults,
    allowedAttributes: {
      ...insane.defaults.allowedAttributes,
      iframe: [],
    },
  });
</script>

<svelte:head>
  <title>Privacy Policy</title>
</svelte:head>

<section class="section">
  <div class="container">
    <div class="content">
      {@html sanitizedPrivacyPolicyContent}
    </div>
  </div>
</section>

// packages/web/src/components/PrivacyPolicy.tsx
import Container from "@material-ui/core/Container";
import MuiHtml from "./MuiHtml";
import { PrivacyPolicyContent } from "@upswyng/common";
import React from "react";

const PrivacyPolicy = () => {
  return (
    <Container>
      <MuiHtml html={PrivacyPolicyContent} />
    </Container>
  );
};

export default PrivacyPolicy;
